version: '3.5'
services:
    php-apache:
        build:
            context: .
            dockerfile: ./docker-php-apache/Dockerfile
        ports:
            - 8080:80
            - 8443:443
        # env_file: ./docker-php-apache/php-apache.env
        environment: 
            CRLIBRE_API_HACIENDA_DB_HOST: 'mariadb'                   # 
            CRLIBRE_API_HACIENDA_DB_NAME: 'testdb'                    # 
            CRLIBRE_API_HACIENDA_DB_USER: 'testuser'                  # 
            CRLIBRE_API_HACIENDA_DB_PASSWORD: 'testpassword'          # 
        depends_on:
            - 'mariadb'
        links:
            - 'mariadb:database'
        networks:
            - app-network
    mariadb:
        image: mariadb:10.11.4
        ports:
            - 4407:3306
        volumes:
            - ./recursos/sql:/docker-entrypoint-initdb.d
            - /var/lib/mysql
        environment:
            TZ: "America/Costa_Rica"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "rootpwd"
            MYSQL_USER: 'testuser'
            MYSQL_PASSWORD: 'testpassword'
            MYSQL_DATABASE: 'testdb'
        restart: always
        tty: true
        networks:
            - app-network
    dotnet-app:
        build:
            context: ./dotnet/LedgerSyncAPI
            dockerfile: Dockerfile.dev
        ports:
            - 5000:8080
            - 5001:443
        volumes:
            - ./dotnet/LedgerSyncAPI:/app  # Asegurar misma estructura
            - ~/.nuget/packages:/root/.nuget/packages:rw  # Cache de paquetes
            - /app/Infrastructure/obj
            - /app/Infrastructure/bin
            - /app/WebAPI/obj
            - /app/WebAPI/bin
        environment:
            ASPNETCORE_ENVIRONMENT: "Development"
            DB_HOST: "mariadb"
            DB_NAME: "testdb"
            DB_USER: "testuser"
            DB_PASSWORD: "testpassword"
        depends_on:
            - mariadb
        networks:
            - app-network
networks:
    app-network:  # Red compartida para todos los servicios
        driver: bridge           