FROM mcr.microsoft.com/dotnet/sdk:9.0

WORKDIR /app

# Copiar solo archivos esenciales primero para caching
COPY *.sln .
COPY Application/*.csproj Application/
COPY Domain/*.csproj Domain/
COPY Infrastructure/*.csproj Infrastructure/
COPY WebAPI/*.csproj WebAPI/

# Restaurar dependencias
RUN dotnet restore

# Instalar herramientas
RUN dotnet tool install --global dotnet-watch

# Instalar depurador (vsdbg)
RUN apt-get update && apt-get install -y unzip \
    && curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg

# Variables de entorno
ENV PATH="${PATH}:/root/.dotnet/tools"
EXPOSE 8080 443 5005 5006

# Especificar el proyecto principal explícitamente con depuración habilitada
ENTRYPOINT ["dotnet", "watch", "run", "--project", "WebAPI", "--urls", "http://*:8080", "--launch-profile", "Development"]
